#+TITLE: 2018 年 Q3
#+DATE: 2018-07-01

* 苹果猝不及防地预发布了新MacBook Pro <2018-07-12 四 21:23>
本来还准备等新版iMac 27和Mac Pro的，这下我多了一种选择。我那使用了快五年的
MacBook Pro也确实需要一个升级了。
- [[https://bbs.ngacn.cc/read.php?tid=14488849][苹果更新MacBook Pro 2018款]]
- [[https://bbs.ngacn.cc/read.php?tid=14488964][macbook pro更新了，换8代cpu]]
- [[http://tieba.baidu.com/p/5792689884][【图片】【新闻】MacBook Pro 2018来了—— 8 代 U 与 32G 内存梦想成真【macbook_百度贴吧]]

* 入手MBP15三日感 <2018-07-24 二 01:48>
新MBP15用起来感觉非常棒，这么大的屏幕、这么高的运算能力给我带来的感觉
就是：真够用。我已经无法回到13寸屏幕的那个年代了。回想一下这几天，真是
如同梦幻。新MBP发布其实没几天，我仿佛是未经思考的一般，不知不觉就把15
寸高配给拎回家了。

* 罕见地感受到了对照相设备的满意 <2018-07-24 二 01:50>
前几天买了A7R3和FE35 2.8。上周末拿着A7R3和FE55以及FE24-240去马路对面的
农学院操场上玩。回家后整理照片，发现效果超乎我的想象。此外我学到一个提
升满意度的要点：回看照片时，不要无限制地放大，苛求每个像素的细节，这没
意义。适度放大看局部即可， *重点体会特定焦距下照片的整体感受* 。

话说回来，A7R3 + FE55 1.8应该是市面上能卖到的锐度最高的组合之一了。

* 读完了《朝闻道》 <2018-07-25 三 13:17>
中午吃饭时候听小乐提到这步刘慈欣的小说，篇幅很短，一小时就能看完。于是
吃完饭后，到工位上，我开始阅读，一会就看完了。
- http://www.jjwxc.net/onebook.php?novelid=32457

* 今天在Mac上折腾安装MySQL花费了一个半小时 <2018-07-26 四 11:45>
我一开始通过brew install mysql安装mysql，但是后来发现用不了，因为用
brew安装的是最新8.0版本，而项目的JDBC只能适配5.X版本的mysql。于是我准
备回退mysql版本，但是总是启动失败。

折腾了很久之后，我决定使用官方的dmg安装包来安装5.6版mysql，但是启动失
败。我仔细看了一下原因，说是：
#+BEGIN_SRC sh
 .\ibdata1 can't be opened in read-write mode
#+END_SRC

看样子是文件权限导致mysql启动失败的。我将官方dmg安装目录
~/usr/local/mysql-5.6.40-macos10.13-x86_64/~ 的属主统一改为自己之后，
发现启动成功。

后来我又发现之前通过brew安装mysql 5.6启动失败可能是因为之前安装mysql 8.0生成的
~/usr/local/var/mysql/~ 目录的数据格式和5.6版本不兼容导致的。我删除掉
这个目录，然后使用：
#+BEGIN_SRC sh
brew install mysql@5.6
#+END_SRC

重新安装mysql 5.6后，发现这次启动成功了！

* 体验到了A7R3后期之乐趣 <2018-09-27 四 01:17>
往青海TB回来后，我的A7R3留下一堆照片和视频，竟达到60G之多！这一度让我
后悔和心力憔悴，我后悔我当时应该买A7M3。

今天从网上搞了一些预设，应用到A7R3拍摄出的照片上面，却产生了让我感到惊
喜和意想不到的效果，尤其是那个Super Chrome预设。

我从中收获到了照片后期的乐趣，也让我暂时断掉换A7R3的念头。
