#+TITLE: 古典音乐
#+DATE: 2015-10-06

* 前言
我喜欢各种各样的音乐，包括畜牧业重金属、新世纪、朋克等，这些年我零星地听过
不少古典音乐并且有些挺喜欢。最近一年，我听的基本都是日本流行音乐和 ACG 音乐，
今天有点腻了，想要拓展我的音乐列表，于是想在古典音乐里挖掘一下。 要成为一位
*古典音乐爱好者* ，需要对古典音乐进行系统的学习和整理，所以开了篇笔记记录一
下。

在西方艺术史里，音乐、建筑、绘画等各项都是相互关联和影响的。例如，我们经常
说的 [[https://zh.wikipedia.org/wiki/%25E5%25B7%25B4%25E6%25B4%259B%25E5%2585%258B%25E8%2589%25BA%25E6%259C%25AF][巴洛克艺术]] 就包括巴洛克建筑、巴洛克音乐、巴洛克油画等。理清一项，对
于西方艺术史的其他各项的理解也会随之加深。

#+BEGIN_QUOTE
古典音乐是指根植于西方音乐传统（包括宗教音乐和世俗音乐）的艺术音乐，包含了
从大约 11 世纪直至当代的广大时间范围。这一艺术传统的中坚时期通常被划定为从
1550 年到 1900 年的这段时间，又称共晓时期。

若依年代来区分，古典音乐可分为以下几个时期：
- 早期古典音乐时期：包括中世纪音乐（500–1400）和文艺复兴音乐（1400–1600）。
- 共晓时期： 包括巴洛克音乐（1600–1750），古典主义音乐（1750–1830）和浪漫主
  义音乐（1804–1910）。
- 现代音乐及当代音乐时期：包括现代音乐（1890–1930），极端现代音乐（20 世纪
  中叶）和当代音乐（1975 至 2000）。
#+END_QUOTE

* 资料收集
- [[https://zh.wikipedia.org/wiki/%25E5%258F%25A4%25E5%2585%25B8%25E9%259F%25B3%25E4%25B9%2590][古典音乐（维基百科）]]

* 体裁
- 交响曲：为管弦乐团创作，包含多个乐章的大型管弦乐曲。
- 奏鸣曲：乐器音乐的写作方式，一般会有三至四个乐章。
- 协奏曲：一件或数件独奏乐器和乐队协同演奏的乐曲。
- 歌剧：主要或完全以歌唱和音乐来交代和表达剧情的戏剧。
- 合唱：集体性的歌唱艺术。人员分成若干声部，分别采用不同的旋律，同时唱歌。
- 室内乐：一种古典音乐作品的体裁，为几件在室内演奏的乐器所作。
  
* 音乐家
- 维瓦尔蒂
- 亨德尔
- 巴赫

* 我的古典音乐歌单

#+BEGIN_HTML
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=450 src="http://music.163.com/outchain/player?type=0&id=113482054&auto=0&height=430"></iframe>
#+END_HTML
** 巴洛克音乐
Hadel 的这首 Entrance of the Queen of Sheba 属于那种非常容易让人喜欢的音乐。
#+BEGIN_HTML
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="http://music.163.com/outchain/player?type=2&id=5211588&auto=0&height=66"></iframe>
#+END_HTML
* 视频
- [[http://v.youku.com/v_show/id_XMTc2NDQ0OTI0.htmlfrom%3Ds1.8-1-1.2][恰空舞曲 巴赫]]
