#+TITLE: 中世纪
#+DATE: 2015-10-06

* 前言
国庆这几天，看完了《三体》全三册，第三册中的魔法师之死一节让我印象深刻，该
节将君士坦丁堡的陷落和宇宙高维碎块联系到一起，对魔法师狄奥伦娜的描写让人印
象深刻。

君士坦丁堡是拜占庭帝国的首都，陷落的年份是 1453 年，其陷落这一时间，一般被
认为是中世纪的结束的标志。《三体》书中提到的皇帝，应该就是君士坦丁十一世。

** 时间
公元 5 世纪到公元 15 世纪。按照历史书的说法，中世纪开始于公元 476 年西罗马
帝国的灭亡，结束于 1453 年东罗马帝国（拜占庭）的灭亡。

* 帝国
* 宗教
基督教内部分为三块：天主教、基督新教和东正教。

* 《极简欧洲史》一书中关于中世纪的文字
#+BEGIN_QUOTE
罗马帝国曾经遭到三次大规模侵略。第一次的侵略者是日耳曼蛮族，继而是穆斯林
（指伊斯兰教徒），再来是北欧人，或称维京人。
#+END_QUOTE

#+BEGIN_QUOTE
当我们谈到罗马帝国的灭亡，总会给它一个年份：公元 476 年。不过，这一年灭亡的只
有西罗马帝国；说希腊语的东罗马帝国以君士坦丁堡为首都，又继续存在了一千年。
#+END_QUOTE
  
#+BEGIN_QUOTE
日耳曼蛮族也曾于公元 3 世纪多次来犯，差点就亡了罗马帝国。当时罗马政权风雨飘摇，
许多皇帝才上台就下台，根本无力抵挡外侮，结果，帝国虽得以苟延残喘，但境内多
处已成了日耳曼人的定居地。君士坦丁大帝，也就是公元 313 年正式宣布支持基督教的
罗马皇帝，在这次战乱后力图整顿，希望重振帝国荣光。
#+END_QUOTE

#+BEGIN_QUOTE
日耳曼民族并没有接掌罗马帝国的欲望。他们只是侵略者，却不想成为征服者。他们
只想分一杯羹，在这块土地上安定下来，过点舒服的日子，所以他们愿意承认罗马帝
王的统治。
#+END_QUOTE
  
#+BEGIN_QUOTE
这是公元 476 年发生的事，不是什么波澜壮阔的最后战役。这位日耳曼领袖叫做奥多亚
克（Odoacer），他接掌了帝国，但并没有自封为帝，而是自称意大利国王。他把西罗
马帝国的王权象征——皇冠和王袍——包好，送到还有另一位皇帝在位的君士坦丁堡去，
等于承认了那位皇帝的治权。日耳曼人沐浴在荣耀之中，这是他们无心插柳下的征服。
#+END_QUOTE
  
#+BEGIN_QUOTE
罗马人判决有罪无罪是以证据和证人为准，日耳曼民族则是用火烧、水淹等酷刑或打
仗。例如，把嫌疑犯的手臂泡在沸水里，如果三天后这只手臂没有痊愈，这人就是有
罪；或是把犯人丢进水里，浮起来就是有罪，沉下去就是无罪。双方若是因土地起争
执可以开战，打胜的一方可以名正言顺宣称所有权。

注：有趣的日耳曼民族
#+END_QUOTE
  
#+BEGIN_QUOTE
在这方面，罗马教廷走的一直是日耳曼路线，直到 12 世纪，教会受到被挖掘出土的
《查士丁尼法典》影响，告诫神职人员不得参与酷刑，情况才有了改变。
#+END_QUOTE
  
#+BEGIN_QUOTE
日耳曼人入侵没多久就转而皈依为基督徒，否定了他们原有的神明或在入侵前曾经改
奉的阿里乌教派（Arianism）。阿里乌教派是基督教一支被视为异端的流派，主要教
义是认为耶稣既是上帝的儿子，各方面势必逊于天父，无法与上帝相提并论。这派主
张曾在东罗马帝国风行过一段时间，之后被传教士带到日耳曼，许多日耳曼人因而成
为该教派信徒。

因此，“罗马的灭亡”在许多方面都有误导之嫌，而最让人误会的是宗教方面——罗马
帝国的国教和教廷其实都幸存下来，甚至受到侵略者的拥抱。这是个起始点，欧洲文
明就此奠基。对此我们前面已经做过表述：日耳曼人支持罗马基督教会，而罗马教会
保存了古希腊罗马的学术。
#+END_QUOTE

#+BEGIN_QUOTE
“法兰西”（France，即法国）这个名字即是法兰克（Franks）的衍生词，因此法国
也是源起于日耳曼民族。法兰克王国于查理大帝（Charles the Great 或 Charlemagne）
在位期间到达鼎盛，他死后王国便告分裂。
#+END_QUOTE

#+BEGIN_QUOTE
之后，盎格鲁（Angles）、萨克森（Saxons）和朱特（Jutes）这几支日耳曼民族于 5
世纪和 6 世纪跨过海峡入侵英格兰。这一回比较像全面的征服；英国人惨遭倾轧，只有
苏格兰、威尔士和英格兰西南部康瓦耳郡（Cornwall）等地逃过一劫。
#+END_QUOTE

#+BEGIN_QUOTE
如此，整个英格兰变成了日耳曼社会；除了众多独立王国林立，它也成了异教之邦，
因为盎格鲁、萨克森和朱特族并不信奉任何流派的基督教。后来爱尔兰和罗马的传教
士来到英格兰，将这些新移民感召成基督徒。关于英国的宗教改奉，爱尔兰扮演了重
要角色，为基督教的存续留下一则动人的篇章。
#+END_QUOTE
  
#+BEGIN_QUOTE
第二次的大侵略来自穆斯林，时为 7 世纪到 8 世纪，距离日耳曼蛮族入侵仅仅两百年。
伊斯兰教始祖穆罕默德原为阿拉伯商人，得到神的天启后创立该教。他这支借由神助
发展出来的宗教，与犹太教和基督教有紧密联系；穆斯林也承认耶稣和耶稣之前的先
知们确实是先知，但深信穆罕默德是世上最后一位先知，能指引大家走向唯一真神安
拉的怀抱。
#+END_QUOTE
  
#+BEGIN_QUOTE
穆罕默德死后，他的信徒继续南征北讨，势如破竹。他们马不停蹄，征服了其他部落
也建立了国邦，先是在波斯帝国地区，后来是东罗马帝国的中东及北非区域。他们沿
着北非继续西进，不但让日耳曼蛮族侵略者所建的王国陷落，之后更越海进入西班牙。
#+END_QUOTE

#+BEGIN_QUOTE
西班牙原是罗马帝国的一个省份，后来被西哥特人（Visigoths）入侵，成为基督教国
家，如今变成了伊斯兰教国家。
#+END_QUOTE  
  
#+BEGIN_QUOTE
在伊斯兰教的统治下，西班牙成了中世纪欧洲最文明的区域。不识字的阿拉伯蛮族南
征北讨，一路上向他们征服的民族学习，包括拥有高度文明的波斯人，和拜占庭帝国
的希腊人。
#+END_QUOTE
  
#+BEGIN_QUOTE
现在，我们要对这二次征战的结果做个归纳。第一，在西欧，日耳曼民族、古罗马和
基督教因此熔于一炉。第二，整个英格兰被日耳曼蛮族占领，之后又回归基督教信仰。
第三，在伊斯兰世界（中东、北非和西班牙），基督教完全隐没，但希腊学术被保存
下来，且被传播到欧洲。
#+END_QUOTE
  
#+BEGIN_QUOTE
维京人，又称诺曼人、北欧人，是最后一批侵略者，在 9 世纪和 10 世纪，也就是继伊斯
兰进占后的两个世纪，横行于整个欧洲。维京人的老家在北方——瑞典、挪威、丹麦，
取道海上来袭。他们的巨大长船委实是个惊人景象，这些船吃水甚浅，只需一米深的
水即可浮起，因此可以长途远航，溯河而上。河水变浅，他们就放下携载于长船上的
小舟，继续航行；遇到障碍，就抬着船只绕过屏障，继续前划。如此这般，他们能够
深入内陆；在俄国境内，从波罗的海直到黑海都有他们的踪迹。
#+END_QUOTE

#+BEGIN_QUOTE
维京人之所以能不断进袭却没有遭受抵抗，是因为政府力薄势弱。它们没有正常的征
税体制，即使有能力整合成军，侵略者也不是从陆路来袭。西欧的小王国没有一个设
有海军，查理大帝麾下从来不曾有过海军编制，再说他的帝国如今已烟消云散。
#+END_QUOTE

#+BEGIN_QUOTE
一段时间后，维京人把妻小都带了来，在这里建立了永久的家园。地图上可以看到他
们的聚落，广布在俄国、法国北部、英格兰和爱尔兰。都柏林原本是北欧人的城市，
英国遭受过两次侵略，第一次是盎格鲁、萨克森和朱特族，之后是从本岛东边进来的
维京人。这两组人马说的都是日耳曼语言，英语就是从它演变而来。法国北方有个移
民区叫做诺曼底（Normandy），就是因为维京人（又称诺曼人）在此定居而得名。法
兰西国王让他们住在这里，条件是要停止掠夺的勾当。

注：诺曼底位于法国北部，诺曼公爵是维京人
#+END_QUOTE
  
#+BEGIN_QUOTE
诺曼人在法国北部定居百年之后，诺曼底公爵威廉带领一些随从于 1066 年征服了英国，
这只是上层阶级的换手；威廉公爵和他的随众开始以英国的新统治者自居。诺曼人说
他们自己的一种法语，之后融合各方语言，最后变成了英语。英国社会到处都是侵略
者，不过 1066 年后就不再有外族入侵。
#+END_QUOTE
  
#+BEGIN_QUOTE
基督教世界的首要任务，是把穆斯林赶回他们的老家。这几次运动动员了整个欧洲，
一开始是为了收复西班牙，继而以夺回圣地耶路撒冷为目标。收复西班牙的行动始于
11 世纪，经过四百余年才大功告成。
#+END_QUOTE
  
#+BEGIN_QUOTE
十字军于 1095 年开始东征圣地，持续攻伐了将近两个世纪。想想看，当这些基督徒知
道耶稣当年的传道之所、葬身之地如今落在离经叛道的异教徒手里，而且这些异教徒
还处处与基督教为敌，势必群情激奋，认为上帝一定希望他们洗刷这样的奇耻大辱。
对于这些圣战，教皇不只鼓励，更予以奖励。不过，这些征战只有第一次获得成功。
#+END_QUOTE
  
#+BEGIN_QUOTE
十字军是多国合作的成果，对比之下，从 15 世纪开始跨海朝美洲和亚洲发展的扩张，
则是几个新兴民族国家间的竞赛——首先是西班牙和葡萄牙，接着是英国、法国和荷兰。
这些国家的首要目标是取得亚洲的香料与财富。它们兵分两路：以海路绕过非洲南部，
或是跨过大西洋直接西进。
#+END_QUOTE
  
#+BEGIN_QUOTE
来自亚洲的奢侈品很早便已传入欧洲，不过都是经由拜占庭帝国的首都君士坦丁堡辗
转而来。欧洲人改采海路，部分原因是陆上的东通之路已经落在穆斯林的手里。
#+END_QUOTE
  
#+BEGIN_QUOTE
7 世纪到 8 世纪，一大块疆土被阿拉伯的伊斯兰教侵略者夺走，9 世纪，土耳其人借道亚
洲大草原接踵而至。他们从东罗马帝国手中夺取了现在称为土耳其的地方，并于南进
和西征途中纷纷改信伊斯兰教，整个中东都落入他们的手中。他们并且翻山越海来到
欧洲，君士坦丁堡周遭的领土相继失陷，四面楚歌。1453 年，土耳其人终于攻占了东
罗马帝国的首都

注：阿拉伯人和土耳其人
#+END_QUOTE
  
#+BEGIN_QUOTE
6 世纪时由查士丁尼大帝所建的圣索菲亚大教堂（Hagia Sophia，意为“天主的上
智”），被改建为伊斯兰教的清真寺。土耳其人本身也建立了一个帝国，称为奥斯曼
帝国。这个帝国于第一次世界大战后画下了休止符，当今的土耳其就此成为一个世俗
国家，虽然绝大部分的人口还是信奉伊斯兰教。
#+END_QUOTE
  
#+BEGIN_QUOTE
君士坦丁堡陷落后，当初将古希腊学术保存下来并仔细研读的基督教学者，亲自带着
这些珍贵手稿逃到了意大利。他们在此受到热烈欢迎，因为文艺复兴学者正四处搜寻
古典文献。
#+END_QUOTE
  
#+BEGIN_QUOTE
有些希腊学术以拉丁原文继续传世，而虽然整个罗马文学深受希腊人影响，但这些希
腊原文作品是在间隔很久并且绕了极远的路之后——中世纪的西班牙以及 15 世纪的君士
坦丁堡——才抵达了西欧。
#+END_QUOTE
