#+TITLE: Screen
#+DATE: 2014-02-16
#+KEYWORDS: Unix 工具, 终端

* Screen 的使用
  时间：2013-8-10 22:51:02
* 如何安装？
  不用安装！screen 是公司机器预装的。

* 如何使用？
也很简单，输入 screen 即可。

* 常用指令：
| 指令          | 作用                                                                                               |
|---------------+----------------------------------------------------------------------------------------------------|
| screen -ls    | 查看所有 session，包括 Attached 的和 Detached 的 session。                                               |
| screen -r xxx | Attach 上已被 detached 的 id 为 xxx 的 session。可以让自己立刻回到上次的工作状态，非常强大。               |
| screen -S xxx | 创建一个名字为 xxx 的 session。注意，如果在.screenrc 里面能把 sessionname 配置项指定了的话，-S 是无效的。 |

* 如何配置？
配置跟 vim 类似，是在~目录下，建立一个~/.screenrc 的文件，在里面写入配置，比如说
screen 状态行（标签行），还有按键映射，自动创建的 session 名字和标签名字等等。下面就
是状态行就是通过配置文件配置出来的：[0$ zy 1-$ zy 2$ zy 3$* zy][ (F8)Detach
(F9)New (F10)Rename (F11)Pre (F12)Next ]

* 按键映射：
可以自由地在~/.screenrc 文件里面设定按键映射。下面是例子：

#+begin_src sh
  #bind F10 to rename current screen window                                                
  bindkey -k k; title                                         
  #bind F11 to move to the previous window                                                 
  bindkey -k F1 prev  
#+end_src

其中 k; 和 F1 为 F10 和 F11 的按键代码，其他所有的按键代码在这里：
 [[http://www.gnu.org/software/screen/manual/html_node/Input-Translation.html#Input-Translation][http://www.gnu.org/software/screen/manual/html\_node/Input-Translation.html#Input-Translation]] 

* 总结：
screen 使用简单，功能强大，提高程序员的工作效率，是个典型的 Unix 风格的软件。

* 问题记录
** screen -S xxx 为何无法成功改名字？
可能是你在~/.screenrc 中设置了 sessionname，注释掉这一行即可。
** 为什么用了 screen 之后经常会闪屏？特别是按 tab 的时候？眼都快被闪瞎了。
闪屏是 screen 提供给用户的一个特性，你可以关掉它。指令是 CTRL+a, CTRL+g。参考[[http://easwy.com/blog/archives/disable-vbell-of-screen/][此文]]。 
** 状态行怎么老是在最下面？能够设置到上面吗？
这个我暂时还不懂，等下周问下同事。
** 为什么修改完~/.screenrc 文件后，不生效？
修改完配置文件是不对已有 screen 生效的，只会对新建立的 session 生效。
** 状态行怎么老是在最下面？能够设置到上面吗？
这个我暂时还不懂，等下周问下同事。
** 我想让新生成的标签页的名字是空的，而不是带有&rdquo;bash&ldquo;的，该怎么做？
默认情况下，新生成的标签的名字为"x$* bash"的字样，如果想让名字为空，好重命名，可以在~/.screenrc 中加入：shelltitle
""，即主动设为空。|
** 为何使用了 screen 之后，我的 F1 到 F4 都不管用了？
可能是你的~/.screenrc 中有这么一行：term linux，这个配置导致你的 F1 和 F4 被屏蔽了，变
成了换行+P 等等。解决方法是去掉这一行，不设置终端（这个配置的作用？）。最后执行
source ~/.screenrc。
** screen 默认的 command key 是\^A，如何更换？
在~/.screenrc 文件中重新绑定即可，例如：escape \^Vv，就可以绑定为\^V，并把
literal command character 设置为 v，最后执行 source ~/.screenrc。参考：
[[http://www.gnu.org/software/screen/manual/screen.html#Command-Character][http://www.gnu.org/software/screen/manual/screen.html#Command-Character]]
** 为何我一切换标签，屏幕缓冲区就立刻被清空？
很可能是你的终端类型没设对。假如你用的是 Mac 上的自带终端，该终端的类型是：
xterm-256color。所以你需要在 termcapinfo 里面加上 xterm-256color。termcapinfo
xterm-256color|xterm|xterms|xs|rxvt ti@:te@
** 如何将各个标签绑定到某个快捷键上：
[[http://stackoverflow.com/questions/4653572/how-do-i-get-the-f1-f12-keys-to-switch-screens-in-gnu-screen-in-cygwin-when-conn][http://stackoverflow.com/questions/4653572/how-do-i-get-the-f1-f12-keys-to-switch-screens-in-gnu-screen-in-cygwin-when-conn]]
